[package]
name = "git-contains"
version = "0.1.0"
authors = ["Dan Aloni <alonid@gmail.com>"]
edition = "2018"

[dependencies]
git2 = "0.13.20"
structopt = "0.3.14"
regex = "1.3.7"
lazy_static = "1.4.0"
ansi_term = "0.12.1"
globset = "0.4"
chrono = "0.4"
thiserror = "1"
